### ISSUE TITLE
WiVRn PC client GUI lobby panel z-fights with skybox in right eye

### ISSUE THREAD

**Issue by SpookySkeletons** [WiVRn/WiVRn#105] opened 2024-08-13 08:29 UTC
Server and headset tested on is monado with the pimax WIP branch

**Comment by xytovl** [comment] 2024-08-13 08:37
This might be caused by initial position of the panel, does it still happen after moving it? controller A button or hand palm pointing up to move it

**Comment by SpookySkeletons** [comment] 2024-08-19 06:27
Yes I did move the lobby panel and it was still affected by this issue

**Comment by xytovl** [comment] 2024-08-20 14:35
Considering the lobby panel is a quad layer and the skybox is a projection layer, this may be a monado bug.

Is it possible to provide a recording of the issue?

**Comment by xytovl** [comment] 2024-10-29 07:44
closing as unable to reproduce

**Closed by xytovl** 2024-10-29 07:44 UTC
