### ISSUE TITLE
Crash on master branch with Pico 4 due to socket error

### ISSUE THREAD

**Issue by Sakugits** [WiVRn/WiVRn#192] opened 2024-12-01 10:48 UTC
Problem description:
I am experiencing a crash when trying to connect my Pico 4 headset using the master branch. Both the application and Envision crash with a socket error.

**Steps to reproduce:**

- Attempt to connect the Pico 4 headset using the master branch.
- Observe the crash in both the application and Envision.
- Repeat the test using TCP-only mode.

**Observed behavior:**

- Both the application and Envision crash with a socket error.
- The issue occurs in both wireless and wired modes.

**Expected behavior:**
The headset should connect without causing the application or Envision to crash.

**Additional details:**

Hardware: Pico 4 headset.

Connection modes tested:

-  Wireless: Crash occurs.
-  Wired (USB-C): Crash occurs.
-  TCP-only mode: Crash persists.

**Question for developers:**
Is there a quick way to test specific commits in Envision to pinpoint when this issue started?

TCP + UDP

![imagen](https://github.com/user-attachments/assets/f4f22a60-cf14-4900-be56-30513da62a0d)

TCP Only

![imagen](https://github.com/user-attachments/assets/599d2336-6697-4480-bc73-fe8586b49968)

**Comment by xytovl** [comment] 2024-12-01 10:51
This is likely a duplicate of https://github.com/WiVRn/WiVRn/issues/190

Do you have logs on client side to know what is crashing?
The socket error just means that the headset disconnected, probably because it crashed.

**Comment by Sakugits** [comment] 2024-12-01 11:19
I've installed the debug APK.

Where can I find the logs?

**Comment by xytovl** [comment] 2024-12-01 11:36
`adb logcat` will collect logs from the headset, you should start the command before doing the connection, it will continue to collect until you stop the adb command.

This works also on release versions, the difference is that in case of crash, the debug apk may provide more details

**Comment by Sakugits** [comment] 2024-12-01 12:18
Thank you!

Here's the log

[12 01 13 10 50 721 1364.txt](https://github.com/user-attachments/files/17968877/12.01.13.10.50.721.1364.txt)

**Comment by xytovl** [comment] 2024-12-01 12:29
I can confirm it is a duplicate, please continue discussion on the other issue

**Closed by xytovl** 2024-12-01 12:29 UTC
