### ISSUE TITLE
[Bug]: Server Doesn't Exit on SIGINT

### ISSUE THREAD

**Issue by damaestro** [WiVRn/WiVRn#214] opened 2024-12-15 20:52 UTC
### Describe the bug

Server stays alive until ctrl-\

### Steps to Reproduce

1. wivrn-server
2. Send ctrl-c

### Expected behavior

Graceful shutdown

### WiVRn Version

wivrn-0.22-1.20241206gitv0.22.fc41.x86_64

### Server Config

```
{
  "bitrate": 50000000,
  "encoders": [
    {
      "codec": "h264",
      "encoder": "vulkan",
      "height": 1.0,
      "offset_x": 0.0,
      "offset_y": 0.0,
      "width": 1.0
    }
  ],
  "tcp_only": false
}

```

### Server Logs

```
WiVRn v0.22 starting
[...]
################################################################################
#                                                                              #
#                        The Monado service has started.                       #
#                                                                              #
################################################################################
 INFO [client_loop] Client 1 connected
 INFO [ipc_handle_instance_describe_client] Client info:
	id: 1
	application_name: 'OpenComposite_hlvr'
	pid: 9711
	extensions:
		ext_hand_tracking_enabled: true
		ext_eye_gaze_interaction_enabled: false
		ext_hand_interaction_enabled: false
 INFO [client_loop] Client disconnected.
^CInterrupt
^CInterrupt
^CInterrupt
^CInterrupt
^CInterrupt
^CInterrupt
^CInterrupt
^CInterrupt
^CInterrupt
^\Quit (core dumped)
```

### What GPU did the bug occur on?

NVIDIA

### What HMD did the bug occur on?

HTC Vive Focus 3

**Comment by damaestro** [comment] 2024-12-15 21:13
This does not occur with encoding set to `nvenc`.

**Comment by xytovl** [comment] 2024-12-15 21:15
Let's close this one in favour of https://github.com/WiVRn/WiVRn/issues/213
The issue is the encoder that hangs waiting on something.

**Closed by xytovl** 2024-12-15 21:15 UTC
Labels: bug
